# Generated by Django 4.2.1 on 2023-05-22 15:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=200)),
                ('credit_hours', models.IntegerField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lecturer')),
            ],
        ),
    ]
