# Generated by Django 4.2.1 on 2023-12-02 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='student_id',
            new_name='student',
        ),
    ]
