# Generated by Django 4.2.1 on 2023-12-11 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_student_profile_picture_datasetimages"),
    ]

    operations = [
        migrations.DeleteModel(name="DatasetImages",),
    ]
