# Generated by Django 4.2.1 on 2024-01-01 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_datasetimages"),
    ]

    operations = [
        migrations.CreateModel(
            name="Leave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("leave_type", models.CharField(max_length=100)),
                (
                    "document",
                    models.FileField(
                        blank=True, null=True, upload_to="leaves_document/"
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="pending", max_length=100)),
                (
                    "attendance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.attendance",
                    ),
                ),
            ],
        ),
    ]
