# Generated by Django 4.2.1 on 2024-01-04 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_leave"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leave",
            name="document",
            field=models.FileField(blank=True, null=True, upload_to="leaves_document"),
        ),
    ]
